
FROM ubuntu:16.04
MAINTAINER Mathew Salvaris <mathew.salvaris@microsoft.com>

RUN mkdir -p /code/flaskwebapp
WORKDIR /code/flaskwebapp
ADD . /code/flaskwebapp/
ADD etc /etc

RUN apt-get update && apt-get install -y --no-install-recommends \
        openmpi-bin \
        python \
        python-dev \
        python-setuptools \
        python-pip \
        supervisor \
        nginx && \
    rm /etc/nginx/sites-enabled/default && \
    cp /code/flaskwebapp/nginx/app /etc/nginx/sites-available/ && \
    ln -s /etc/nginx/sites-available/app /etc/nginx/sites-enabled/ && \
    pip install -r /code/flaskwebapp/requirements.txt && \
    pip install https://cntk.ai/PythonWheel/CPU-Only/cntk-2.0rc1-cp27-cp27mu-linux_x86_64.whl
    
ENV PYTHONPATH $PYTHONPATH:/code/flaskwebapp/:/code:/code/flaskwebapp

EXPOSE 88
CMD ["supervisord", "-c", "/etc/supervisord.conf"]
